import Footer from '../components/Footer';
import Header from '../components/Header';
import Navigation from '../components/Navigation';
import './globals.css';
import { JetBrains_Mono } from 'next/font/google';

const jetBrainsMono = JetBrains_Mono({ weight: '400', subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={jetBrainsMono.className}>
        <Header />
        <Navigation />
        <main className="min-h-screen h-full">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
